更新wpi-update

diff --git a/server/wpi-update b/server/wpi-update
--- a/server/wpi-update
+++ b/server/wpi-update
@@ -12,6 +12,7 @@ RELEASE_FILE="/etc/WalnutPi-release"
 FILE_LOG_SAVE="/tmp/wpi-update-update.log"
 FILE_PACKAGES="/tmp/wpi-update-packages.txt"
 
+
 run_status() {
     local message=$1
     shift
@@ -45,16 +46,6 @@ echo_blue() {
 }
 
 
-echo_auto_detect() {
-    str_cn=$1
-    str_en=$2
-    if [[ $LANG ==  zh_CN* ]]; then
-        echo -e $str_cn
-    else
-        echo -e $str_en
-    fi
-}
-
 declare -A STR_CN
 declare -A STR_EN
 declare -A STR_AUTO
@@ -62,7 +53,7 @@ declare -A STR_AUTO
 STR_CN['sudo_warn']="\n\t请使用sudo来运行本指令\n"
 STR_EN['sudo_warn']="\n\tError:  please use sudo !\n"
 
-STR_CN['version_newest_h']="\n\t你的系统版本已经是最新的  ,无需更新\n"
+STR_CN['version_newest_h']="\n\t你的系统版本已经是最新的  ,无需更新"
 STR_CN['version_newest_l']="  ,无需更新\n"
 STR_EN['version_newest_h']="\n\tYour system version is already up to "
 STR_EN['version_newest_l']="  ,No need to update\n"
@@ -113,11 +104,12 @@ FLAG=$1
 
 
 # 从文件中获取版本号和日期
-BOARD_VER=$(grep '^version=' $RELEASE_FILE | cut -d '=' -f 2)
-BOARD_DATE=$(grep '^date=' $RELEASE_FILE | cut -d '=' -f 2)
-# echo "BOARD_VER: $BOARD_VER"
-# echo "BOARD_DATE: $BOARD_DATE"
-
+if [[ -f $RELEASE_FILE ]]; then
+    BOARD_VER=$(grep '^version=' $RELEASE_FILE | cut -d '=' -f 2)
+    BOARD_DATE=$(grep '^date=' $RELEASE_FILE | cut -d '=' -f 2)
+    # echo "BOARD_VER: $BOARD_VER"
+    # echo "BOARD_DATE: $BOARD_DATE"
+fi
 
 
 # 获取网站上存储的本脚本,进行更新
@@ -127,7 +119,10 @@ if [[ $FLAG != "no_update" ]]; then
     fi
     run_status "update this script ...."  wget -c $THIS_SCRIPT_URL -O $THIS_SCRIPT_SAVE
     NEW_SCRIPT_VERSION=$(grep -o 'THIS_SCRIPT_VERSION=[0-9.]*' $THIS_SCRIPT_SAVE | cut -d '=' -f 2)
-    # echo "新版本=$NEW_SCRIPT_VERSION"
+    # if [[ $* =~ -v ]]; then
+    #     echo "新版本=$NEW_SCRIPT_VERSION"
+    # fi
+
     if [[ "$NEW_SCRIPT_VERSION" > "$THIS_SCRIPT_VERSION" ]]; then
         cp $THIS_SCRIPT_SAVE $0
         exec bash $0 no_update
@@ -157,7 +152,10 @@ for DATE in $DATES_IN_LOG; do
     fi
 done
 NEW_VERSION=$(grep -o '\[[^]]*\] - [^ ]*' $FILE_LOG_SAVE | head -n 1 | awk '{print $3}')
-
+if [[ $* =~ -v ]]; then
+    echo "新版本= $NEW_VERSION "
+    exit 0
+fi
 
 if [ -z "$HAS_NEW" ]; then
     echo -e  "${STR_AUTO['version_newest_h']}[${NEW_VERSION}]${STR_AUTO['version_newest_l']}"
@@ -171,12 +169,17 @@ echo -e "${STR_AUTO['backup_warn']}"
 
 sed -n "1,/\\[$LAST_DATE\\]/p" $FILE_LOG_SAVE | sed '/\['$LAST_DATE'\]/d'
 echo -n "${STR_AUTO['are_u_redy']} "
-read -p "[Y/n]" CHOICE
-if [[ "$CHOICE" != "y" && "$CHOICE" != "Y" ]]; then
-    echo -e "${STR_AUTO['abort']}."
-    exit 1
-fi
 
+if [[ $* =~ -y ]] || [[  $* =~ -Y ]]; then
+    echo ""
+else
+    read -p "[Y/n]" CHOICE
+    if [[ "$CHOICE" != "y" && "$CHOICE" != "Y" ]]; then
+        echo -e "${STR_AUTO['abort']}."
+        exit 1
+    fi
+
+fi
 
 # 获取更新，安装
 run_status "get the package info ..." apt-get update -o Dir::Etc::sourcelist="$TMP_SOURCE_FILE" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
