[update] goodix-ts-auto-rotation add support for jd9366

diff --git a/main/goodix-ts-auto-rotation/usr/lib/walnutpi/goodix-ts-auto-rotation b/main/goodix-ts-auto-rotation/usr/lib/walnutpi/goodix-ts-auto-rotation
--- a/main/goodix-ts-auto-rotation/usr/lib/walnutpi/goodix-ts-auto-rotation
+++ b/main/goodix-ts-auto-rotation/usr/lib/walnutpi/goodix-ts-auto-rotation
@@ -33,6 +33,15 @@ bind_ts_to_dsi1() {
     fi
     xinput map-to-output ${TS_DEVICE_ID} DSI-1
 }
+bind_jd9366_to_dsi1() {
+    export DISPLAY=:0
+    TS_DEVICE_ID=$(xinput list --id-only 'wpi-jd9366-touch')
+    if [ $? -ne 0 ]; then
+        echo "Failed to get TS device ID"
+        return
+    fi
+    xinput map-to-output ${TS_DEVICE_ID} DSI-1
+}
 
 # 等待直到x11启动
 wait_for_x11() {
@@ -47,18 +56,35 @@ main() {
     wait_for_x11
     Board_model=$(tr -d '\0' </proc/device-tree/model)
     source /etc/WalnutPi-release
+
+    # 根据LCD类型确定使用的触摸屏设备绑定函数
+    local bind_function=""
     if [ "x$lcd" == "xdsi-1920x1080" ]; then
-        while true; do
-            current_rotation=$(xrandr --query | grep DSI-1 | awk '{print $4}')
-            if [ "$current_rotation" != "$last_rotation" ]; then
-                auto_rotate "$current_rotation"
-                last_rotation="$current_rotation"
-            fi
-            if [ "x$Board_model" == "xwalnutpi-2b" ]; then
-                bind_ts_to_dsi1
-            fi
-            sleep 1
-        done
+        bind_function="bind_ts_to_dsi1"
+    elif [ "x$lcd" == "xdsi-1280x800" ]; then
+        bind_function="bind_jd9366_to_dsi1"
+    else
+        # 不支持的LCD类型，退出程序
+        exit 0
     fi
+
+    # 根据板型确定是否需要绑定触摸屏
+    local needs_binding=false
+    if [ "x$Board_model" == "xwalnutpi-2b" ]; then
+        needs_binding=true
+    fi
+
+    while true; do
+        current_rotation=$(xrandr --query | grep DSI-1 | awk '{print $4}')
+        if [ "$current_rotation" != "$last_rotation" ]; then
+            auto_rotate "$current_rotation"
+            last_rotation="$current_rotation"
+            if [ "$needs_binding" = true ]; then
+                $bind_function
+            fi
+        fi
+
+        sleep 1
+    done
 }
 main
